name: github pages

on:
  push:
    branches:
      - master  # 每次推送到 main 分支都会触发部署任务

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.106.0'
          extended: true
      
      - name: Clean
        run: cd public && rm -rf `ls -A1 | grep -v .git` && cd ..

      - name: Build
        run: hugo  -t jane -b "https://guabutian.github.io/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: guabutian/guabutian.github.io   # 替换成上文所创建的个人主页仓库
          publish_branch: master
          publish_dir: ./public
